#include "../../api.c"

void print_test_started(char * in_test_name)
{
	printf("\nStarting %s ...", in_test_name);
}

void print_test_outcome(int in_outcome, char * in_test_name)
{
	if(in_outcome == 0){
		printf("\n... **********%s has failed!**********", in_test_name);
	}
	else if(in_outcome == 1){
		printf("\n... passed");
	}
}


void test_delete_project()
{
	print_test_started("test_delete_project");

	LinkedList * list = create_list();
	char * filename = "reserved_test_project_name.prj";
	
        Project * test_project = create_project(list, "Test Project",
			  "This is a test project generated by the test suite");
	save_project(test_project, filename);

	if(open_project(filename) != NULL){
		print_test_outcome(1, "test_delete_project");
	}

	else{
		print_test_outcome(0, "test_delete_project");
	}
	
	
}

void test_open_project()
{
	//TODO: 

}


void test_save_project()
{
	//TODO:
	
}



void run_io_tests()
{
	
	test_open_project();
	test_save_project();
	test_delete_project();
}

